Decrease resolution of candle data
get:
ValueError: all the input array dimensions for the concatenation axis
must match exactly, but along dimension 0, the array at index 0 has size
2190 and the array at index 1 has size 2186

because:
DP.clean_data(data) doesn't work correctly, after clean_data, some ticket has still different shape