issue-2230941451 by manu1dcb on 8 April 2024 resolved (#1203)
* issue-2230941451(**TypeError:** DRLEnsembleAgent.run_ensemble_strategy() missing 1 required positional argument: 'timesteps_dict') in file examples/FinRL_Ensemble_StockTrading_ICAIF_2020.ipynb  created by manu1dcb resolved

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

---------

Co-authored-by: Ubuntu <ubuntu@ip-172-31-6-116.ap-southeast-2.compute.internal>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>